#!/bin/bash
set -eu

# It seems that in conky the execi command will start before curl has completely
# written the file. For some reason adding a sleep before calling curl fixes it.
sleep 2

forecast=~/".cache/forecast.json"
weather=~/".cache/weather.json"

mkdir -p ~/".cache/harmattan-conky"

api_prefix="api.openweathermap.org/data/2.5/"

appid="APPID=4e68bd12fdabd3a64051ea35812465f3"
id="&q=Nanjing,CN"
units="&units=metric"
lang="&lang=zh_cn"

curl -s "${api_prefix}forecast?${appid}${id}${units}${lang}" -o "$forecast"
curl -s "${api_prefix}weather?${appid}${id}${units}${lang}" -o "$weather"
