#!/bin/bash

if [[ -n $BLOCK_INSTANCE ]]; then
  IF=$BLOCK_INSTANCE
else
  IF=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------

#if [[ ${BLOCK_BUTTON} -eq 1 ]]; then
#  if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
#    sudo ip link set $IF up
#    sudo systemctl restart NetworkManager
#  else
#    sudo ip link set $IF down
#  fi
#fi

if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo " off"
  echo " off"
  exit
fi

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

SSID_NAME=$(iwgetid -r)

device="${BLOCK_INSTANCE:-wlp2s0}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

quality=100
if [[ "${status}" == "up" ]]; then
  quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
fi

INSTANCE="${BLOCK_INSTANCE}"
# If you don't like you can use any other IP
INTERFACE="$(ip route get 8.8.8.8 | grep -Po '(?<=(dev )).*(?= src)')"

if [[ "${INSTANCE}" = "" ]]; then
  INSTANCE="${INTERFACE};both"
fi

INSTANCE=$(echo "${INSTANCE}" | awk -F ';' '{print $1}')

ONE_KB=1024
ONE_MB=$(echo "${ONE_KB}*1024" | bc -l)
TEN_MB=$(echo "${ONE_MB}*10" | bc -l)
OHD_MB=$(echo "${TEN_MB}*10" | bc -l)

PREV_IN=0
PREV_OUT=0

PREV_FILE="/tmp/.bandwidth"

if [[ -f "${PREV_FILE}" ]]; then
  PREV_CONT=$(cat "${PREV_FILE}")
  PREV_IN=$(echo "${PREV_CONT}" | head -n 1)
  PREV_OUT=$(echo "${PREV_CONT}" | tail -n 1)
fi

BANDWIDTH=$(grep "${INSTANCE}" /proc/net/dev | awk -F: '{print  $2}' | awk '{print $1" "$9}')

if [[ "${BANDWIDTH}" = "" ]]; then
  exit
fi

BYTES_IN=$(echo "${BANDWIDTH}" | awk -F ' ' '{print $1}')
BYTES_OUT=$(echo "${BANDWIDTH}" | awk -F ' ' '{print $2}')

function FormatNumber() {
  if [[ "${1}" -ge "${OHD_MB}" ]]; then
    echo $(echo "scale=0;${1}/${ONE_MB}" | bc -l)"M/S"
  elif [[ "${1}" -ge "${TEN_MB}" ]]; then
    echo $(echo "scale=1;${1}/${ONE_MB}" | bc -l)"M/S"
  elif [[ "${1}" -ge "${ONE_MB}" ]]; then
    echo $(echo "scale=2;${1}/${ONE_MB}" | bc -l)"M/S"
  elif [[ "${1}" -ge "${ONE_KB}" ]]; then
    echo $(echo "scale=0;${1}/${ONE_KB}" | bc -l)"K/S"
  else
    echo "${1}""B/S"
  fi
}

if [[ "${PREV_IN}" != "" ]] && [[ "${PREV_OUT}" != "" ]]; then
  # Calculate the CPU usage since we last checked.
  DIFF_IN=$(echo "scale=0;${BYTES_IN} - ${PREV_IN}" | bc -l)
  DIFF_OUT=$(echo "scale=0;${BYTES_OUT} - ${PREV_OUT}" | bc -l)

  USAGE_IN=$(FormatNumber "${DIFF_IN}")
  USAGE_OUT=$(FormatNumber "${DIFF_OUT}")

fi

# Remember the total and idle CPU times for the next check.
echo "${BYTES_IN}" > "${PREV_FILE}"
echo "${BYTES_OUT}" >> "${PREV_FILE}"

if [[ "${SSID_NAME}" != "" ]]; then
  echo "[${quality}%][${SSID_NAME}][$IPADDR]${USAGE_IN}${USAGE_OUT}" # full text
  echo "[${quality}%][${SSID_NAME}][$IPADDR]${USAGE_IN}${USAGE_OUT}" # full text
fi

if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi

