#!/bin/bash

[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------
IFs=$( ls "/sys/class/net/" )
ETH="nil"
WLAN="nil"

for entry in $IFs ; do
    if [[ $entry == enp* ]] ; then
        ETH=$entry
    elif [[ $entry == wlp* ]] ; then
        WLAN=$entry
    fi
done

is_eth=1
if [[ "$(cat /sys/class/net/$ETH/operstate)" = 'up' ]]; then
    IF=$ETH
elif [[ "$(cat /sys/class/net/$WLAN/operstate)" = 'up' ]]; then
    IF=$WLAN
    is_eth=0
else
    echo " off"
    echo " off"
    exit
fi

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

URGENT_VALUE=10

if [[ $is_eth -eq 0 ]] ; then
    SSID_NAME=$(iwgetid -r)
    quality=$(grep ${IF} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
fi

BD=$(vnstat -i "$IF" -tr -s)
USAGE_IN=$(echo "$BD" | grep "rx" | awk '{ print $2 $3 }')
USAGE_OUT=$(echo "$BD" | grep "tx" | awk '{ print $2 $3 }')

if [[ $is_eth -eq 0 ]] ; then
    if [[ "${SSID_NAME}" != "" ]]; then
        echo " [${quality}%][${SSID_NAME}][$IPADDR]  ${USAGE_IN}  ${USAGE_OUT}" # full text
        echo " [${quality}%][${SSID_NAME}][$IPADDR]  ${USAGE_IN}  ${USAGE_OUT}" # full text
    fi
elif [[ $is_eth -eq 1 ]] ; then
    echo " $IPADDR  ${USAGE_IN}  ${USAGE_OUT}" # full text
    echo " $IPADDR  ${USAGE_IN}  ${USAGE_OUT}" # full text
    exit
    if [[ $IPADDR == "" ]] ; then
        echo " off"
        echo " off"
        exit
    fi
fi

if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi

