#!/bin/bash

[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------
IFs=$( ls "/sys/class/net/" )
ETH="nil"
WLAN="nil"

for entry in $IFs ; do
    if [[ $entry == enp* ]] ; then
        ETH=$entry
    elif [[ $entry == wlp* ]] ; then
        WLAN=$entry
    fi
done

is_eth=1
if [[ "$(cat /sys/class/net/$ETH/operstate)" = 'up' ]]; then
    IF=$ETH
elif [[ "$(cat /sys/class/net/$WLAN/operstate)" = 'up' ]]; then
    IF=$WLAN
    is_eth=0
else
    echo " off"
    echo " off"
    exit
fi

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

URGENT_VALUE=10

if [[ $is_eth -eq 0 ]] ; then
    SSID_NAME=$(iwgetid -r)
    quality=$(grep ${IF} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
fi

INSTANCE=${IF}

ONE_KB=1024
ONE_MB=$(echo "${ONE_KB}*1024" | bc -l)
TEN_MB=$(echo "${ONE_MB}*10" | bc -l)
OHD_MB=$(echo "${TEN_MB}*10" | bc -l)

PREV_IN=0
PREV_OUT=0

PREV_FILE="/tmp/.bandwidth"

if [[ -f "${PREV_FILE}" ]]; then
  PREV_CONT=$(cat "${PREV_FILE}")
  PREV_IN=$(echo "${PREV_CONT}" | head -n 1)
  PREV_OUT=$(echo "${PREV_CONT}" | tail -n 1)
fi

BANDWIDTH=$(grep "${INSTANCE}" /proc/net/dev | awk -F: '{print  $2}' | awk '{print $1" "$9}')

if [[ "${BANDWIDTH}" = "" ]]; then
    exit 33
fi

BYTES_IN=$(echo "${BANDWIDTH}" | awk -F ' ' '{print $1}')
BYTES_OUT=$(echo "${BANDWIDTH}" | awk -F ' ' '{print $2}')

function FormatNumber() {
  if [[ "${1}" -ge "${OHD_MB}" ]]; then
    echo $(echo "scale=0;${1}/${ONE_MB}" | bc -l)"M/s"
  elif [[ "${1}" -ge "${TEN_MB}" ]]; then
    echo $(echo "scale=1;${1}/${ONE_MB}" | bc -l)"M/s"
  elif [[ "${1}" -ge "${ONE_MB}" ]]; then
    echo $(echo "scale=2;${1}/${ONE_MB}" | bc -l)"M/s"
  elif [[ "${1}" -ge "${ONE_KB}" ]]; then
    echo $(echo "scale=0;${1}/${ONE_KB}" | bc -l)"K/s"
  else
    echo "${1}""B/s"
  fi
}

if [[ "${PREV_IN}" != "" ]] && [[ "${PREV_OUT}" != "" ]]; then
  # Calculate the CPU usage since we last checked.
  DIFF_IN=$(echo "scale=0;${BYTES_IN} - ${PREV_IN}" | bc -l)
  DIFF_OUT=$(echo "scale=0;${BYTES_OUT} - ${PREV_OUT}" | bc -l)

  USAGE_IN=$(FormatNumber "${DIFF_IN}")
  USAGE_OUT=$(FormatNumber "${DIFF_OUT}")
fi

# Remember the total and idle CPU times for the next check.
echo "${BYTES_IN}" > "${PREV_FILE}"
echo "${BYTES_OUT}" >> "${PREV_FILE}"

if [[ $is_eth -eq 0 ]] ; then
    if [[ "${SSID_NAME}" != "" ]]; then
        echo " [${quality}%][${SSID_NAME}][$IPADDR]  ${USAGE_IN}  ${USAGE_OUT}" # full text
        echo " [${quality}%][${SSID_NAME}][$IPADDR]  ${USAGE_IN}  ${USAGE_OUT}" # full text
    fi
elif [[ $is_eth -eq 1 ]] ; then
    echo " $IPADDR  ${USAGE_IN}  ${USAGE_OUT}" # full text
    echo " $IPADDR  ${USAGE_IN}  ${USAGE_OUT}" # full text
    exit
    if [[ $IPADDR == "" ]] ; then
        echo " off"
        echo " off"
        exit
    fi
fi

if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi

