#!/usr/bin/env bash

if [[ "$1" == "on" ]];
then
    sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
    echo "Disable Sleep / Suspend / Hibernate."
elif [[ "$1" == "off" ]];
then
    sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target
    echo "Enable Sleep / Suspend / Hibernate."
fi
